### ISSUE TITLE
是否可以將 submodule PyPtt 改為直接引用?

### ISSUE THREAD

**Issue by PttCodingMan** [openopentw/PTT-web-backend#1]
Hi,
請問一下，有特別將 PyPtt 當成 sub module 的原因?
以我的角度來看，不如直接使用 PyPi 上的 PyPtt?

若您允許的話，我可以發個 PR。

CodingMan

**Comment by openopentw** [comment]
之前是因為開看板的時候
會因為已刪除文章跑得很慢
所以我才 fork PyPtt 修正這個問題
並讓這個 repo 使用我修改過的 PyPtt

不過後來你把我修正過的版本 merge 進去了
所以的確引用 PyPi 上的 PyPtt 會比較好
遇到問題要回報的話也會比較準確

你可以發個 PR
或者改天我有空也可以自己改一改XD

**Comment by PttCodingMan** [comment]
原來是這樣，我看看哪時候來修改一下，感謝回覆
